### ISSUE TITLE
MAGStock 7: Band Plugin creates Groups Wrong

### ISSUE THREAD

**Issue by Hachi05** [magfest/magstock#129]
Band Plugin spawned Groups should be created with all badges free. Currently, a Group Leader is marked Paid: Doesn't need to, and everyone else Paid By Group. (Except for Wreck the System which has two people created by non-admin who are marked Does not need to pay??)

I think all members need to be created as Paid: Doesn't need to.

We should not even let people 'pay' $0 for anything.

Note though, when you switch someone from Paid by group to Paid: Doesn't need to, the Group Leader can no longer say that person is no longer coming as that option disappears.

**Comment by Hachi05** [comment]
edited post once I realized what was REALLY happening.

**Comment by kitsuta** [comment]
Having paid-by-group badges inside free groups is something that MAGPrime does constantly. RAMS is not an auditing tool, so in this case I would definitely favor better functionality (letting group leaders mark people as not coming) over accurate 'payment' numbers -- you did not specify _why_ "we should not even let people 'pay' $0 for anything." Why not?

The original issue you filed stated:
"This issue is throwing off what is on the Statistics Page since it looks like they paid... even though they paid 0$... yeah, don't let people pay 0$"

So based on that, is the 'why not' because the stats page is wrong? If so, a better way to go might be to fix the statistics page so it doesn't count people who've "paid by group" when the group is free. That way the stats page will be correct and the group leader will still be able to manage their group's badges. Does that sound good?

**Comment by kitsuta** [comment]
Oh right, also, the Bands plugin doesn't create groups. If you look in the group's history, you'll see that they were created by hand by an admin.

So... probably fixing the statistics page is a good option!

**Comment by Hachi05** [comment]
Fixed by https://github.com/magfest/bands/commit/b721df41a55bc4bb087af6115d01da1f5a27fb6b.

**Comment by kitsuta** [comment]
Are you, er, sure about that?

1. The groups in Magstock were made before the bands plugin could create groups, so they were all made by hand -- there was nothing in code to fix about group creation.
2. The commit you linked to specifically makes badges inside the group `paid_by_group` which is what you said you DIDN'T want.

If you could describe what's going on with the stats page that isn't working for you, we can use this issue to track that and then fix it.
