### ISSUE TITLE
As a staffer, I shouldn't see $20 food drop down because food is included in my registration

### ISSUE THREAD

**Issue by cybersenshi** [magfest/magstock#68]
Staff should not see the $20 food kickin option, as staff get food by default.
Should be an option for those planning to sleep in the manor house rather than camp.

**Comment by binary1230** [comment]
Hey, when making these, since it's a feature request, use the story format when possible. For this one:  "As a staffer, I shouldn't see $20 food drop down because food is included in my registration"

**Comment by cybersenshi** [comment]
That doesn't include the manor house part at all.
Do you want it as a separate thing?

**Comment by binary1230** [comment]
Guess I misunderstood, we'll need to specify some details about how to know who is supposed to get this benefit or not.  All staff? Select staff?  How does uber know who is supposed to get food or not?

**Comment by cybersenshi** [comment]
Staff gets food. Bands get food. All others it's a kickin.
Staff should have an "I'm expecting to sleep in the manor house" option, so we have an idea of how many sleeping spaces should be accounted for.

**Comment by kitsuta** [comment]
And this is why the story format is good - it's easy for grammar to get confusing.

So this would be:
"As a staffer, I should not see the $20 food kick-in option, because food is included in my registration. I should also be able to select a "Manor House" housing option, since I may be planning to sleep in the staffing Manor house."

Ideally that would be two issues, but the story format makes it clear what the conditions of a feature are.

**Comment by binary1230** [comment]
actually fixed this up so all staff, and separately, anyone in a group that is marked as a band (including musicians and their +1s) automatically gets food and it says "free food"

**Comment by kitsuta** [comment]
We don't have an issue for the manor house option though, right?

**Comment by binary1230** [comment]
True

**Comment by kitsuta** [comment]
#87.
